### ISSUE TITLE
Promtail saturates CPU

### ISSUE THREAD

**Issue by mazzy89** [mdegat01/addon-promtail#122]
**Describe the bug**
Promtail saturates CPU

**To Reproduce**

1. Install Promtail
2. Start it
3. Run Loki
4. Check CPU usage of the Promtail container

**Expected behavior**

Promtail should not saturate

**Logs**

```
Include any relevant logs
```

**Environment (please complete the following information):**

- Add-on version: 1.6.1
- Supervisor version: supervisor-2021.06.8
- Operating system Home Assistant OS 5.4.83-v8

**Additional context**

<img width="708" alt="Screenshot 2021-08-07 at 12 19 53" src="https://user-images.githubusercontent.com/5463218/128597033-61baa718-ddb2-4d3a-a8e3-1f11b4a5726a.png">

I would need to troubleshoot promtail process.

**Comment by mazzy89** [comment]
I've noticed that I had to leave it running for a while before getting ok. I think it was saturating because of the indexing operation at the first bootstrap.

**Comment by mdegat01** [comment]
Hm so when you first turn this addon on assuming your using the default config it will start going through your entire systemd journal. Everything on your system logs there and it survives restarts so that is a lot of information to go through.

So if you just turned it on on an rpi or something you've had running stuff for a while it doesn't seem that surprising that it would have a lot of work to do indexing all the existing logs. Eventually it should catch up to reality and stabilize. Maybe let it run for a bit longer to see if it levels out? Or could try clearing out your journal to let it start from a blank slate if you just want to index from here on out.

Not entirely sure what I can do about it otherwise though. Promtail isn't my software, I just repackaged it in a form compatible with home assistant. So if it continues to chew up unbounded cpu you'll likely have to report an issue on the [loki+promtail repo](https://github.com/grafana/loki).

**Comment by mazzy89** [comment]
Now everything looks fine

<img width="704" alt="Screenshot 2021-08-07 at 14 31 46" src="https://user-images.githubusercontent.com/5463218/128600340-2a296827-8a39-4490-8f12-21a8806f9473.png">

And promtail is doing its nice job.

Thanks @mdegat01 

We can close this
